### ISSUE TITLE
LassoNet for multiple input multiple output problems (sensors selection for physics field decoder challenge)

### ISSUE THREAD

**Issue by IDoytchinov** [lasso-net/lassonet#1]
Dear all, we are working on physics guided AI where we wish to use several sensors to decode a full aerodynamics field of interest (https://royalsocietypublishing.org/doi/10.1098/rspa.2020.0097). Our decoder works well. However, we wish to optimise the sensor placement that will have the best results for decoding the aerodynamic field.

This leaves us with let's say 5- 30 or 100 input to the decoder and several thousand or hundreds of thousands of outputs. How can we apply LassoNet to our problem when we want to optimise the overall (several thousand) output decoded field quality?

i.e. study which input sensor features are most important for the 'genera' field reconstruction (minimum error at all outputs together). Multiple inputs - multiple output SHAP.

If you have any ideas or have heard of such an application of Lassonet please can you let us know!?

image

Iordan Doytchinov, Ph.D.

Postdoctoral researcher and scientific collaborator

Ecole Polytechnique Fédérale de Lausanne (EPFL)
EPFL – TOPO
Station 18 – Bâtiment GC C2 398

CH–1015 Lausanne

Office telephone: +41216939832
Personal mobile: +33699850592

iordan.doytchinov@epfl.ch
http://topo.epfl.ch/

**Comment by louisabraham** [comment]
Hi, it looks indeed like a feature selection problem. You can use [LassoNetRegressor](https://louisabraham.github.io/lassonet/api/#lassonet.LassoNetRegressor), compute a path and look at the features that are selected. In the latest version of the library (not yet on PyPI), after training, you can access `feature_importances_`.

I'm not sure of the default parameters you should use (particularly for the path start). I'm working on adding regression examples but for the moment you can probably look at [this one](https://github.com/louisabraham/lassonet/blob/master/examples/run_demo_mice.py), just use a Regressor instead of a Classifier!

**Comment by louisabraham** [comment]
Following our exchanges by email, I hope LassoNet has been useful to you! Closing this for now.

**Comment by IDoytchinov** [comment]
Thanks a lot Louis!

________________________________
